---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Install the apache2 package
    apt: 
      name: apache2
      state: latest

  - name: Add PHP suport for apache
    apt: 
      name: libapache2-mod-php
      state: latest
