---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: Install the apache and php support packages
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install the apache and php support packages
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"


- hosts: db_servers
  become: true
  tasks:
     
  - name: Install mongoDB 
    apt:
      name: mongodb
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install MongoDB for CentOS
    yum:
      name: mongodb-org
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:

  - name: Install Samba fileserver
    package:
      name: samba
      state: latest
    
